#!/usr/bin/env python3

import sys
import os
import urllib.request
import json

def install_nvm():
    with urllib.request.urlopen("https://api.github.com/repos/creationix/nvm/releases/latest") as nvm_url:
        data = json.loads(nvm_url.read().decode())
        latest_tag = data["tag_name"]
        print("latest version of nvm is %s" % latest_tag)
        down_nvm_url = "https://raw.githubusercontent.com/creationix/nvm/" + latest_tag + "/install.sh"
        os.system("curl -o- "+down_nvm_url+" | bash")


def install_ohmyzsh():
    os.system('sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"')


def main(args):
    arg = args[1]
    if arg in ("-h", "--help"):
        print("plus <apps>")
    elif arg == "nvm":
        install_nvm()
    elif arg in ("oh_my_zsh", "oh-my-zsh", "ohmyzsh"):
        install_ohmyzsh()
    else:
        print("Unknown input. Aborted.")
        sys.exit(1)


if __name__ == "__main__":
    main(sys.argv)
